name: Deploy Docker Compose using Local Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Build Docker images
#        run: docker-compose build

      - name: Deploy Docker Compose
        run: docker-compose -f pwd.yml up -d
