name: Deploy to localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Connect to localhost
      uses: appleboy/ssh-action@master
      with:
        host: decoders-ThinkPad-T470-W10DG
        username: decoders
        password: ${{ secrets.LOCAL_PASSWORD }}
        port: 22

    - name: Start new container
      run: ssh decoders@decoders-ThinkPad-T470-W10DG docker-compose up -d
      