name: Deploy to localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Connect to localhost
      uses: appleboy/ssh-action@master
      with:
        host: 13.233.109.71
        username: ubuntu
        password: ${{ secrets.LOCAL_PASSWORD }}
        port: 22

    - name: Start new container
      run: ssh ubuntu@13.233.109.71 docker-compose up -d
      